server {
    listen 80;
    
    # Корневая папка, куда мы скопировали файлы в Dockerfile
    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        # Если файл не найден, отдаем index.html (нужно для SPA роутинга)
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}